"""Pytest configuration: Hypothesis profiles, fuzz markers, and skip reporting."""

from __future__ import annotations

import hashlib
import json
import textwrap
import time
from pathlib import Path

import pytest
from hypothesis import HealthCheck, Phase, Verbosity, settings

# ---------------------------------------------------------------------------
# Hypothesis profiles
# ---------------------------------------------------------------------------
settings.register_profile(
    "dev",
    max_examples=500,
    deadline=200,
    phases=list(Phase),
)

settings.register_profile(
    "ci",
    max_examples=50,
    deadline=200,
    phases=list(Phase),
    derandomize=True,
    print_blob=True,
)

settings.register_profile(
    "verbose",
    max_examples=100,
    deadline=200,
    phases=list(Phase),
    verbosity=Verbosity.verbose,
)

settings.register_profile(
    "hypofuzz",
    max_examples=10000,
    deadline=None,
    phases=list(Phase),
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)

settings.register_profile(
    "stateful_fuzz",
    max_examples=500,
    deadline=None,
    phases=list(Phase),
)

settings.load_profile("ci")


# ---------------------------------------------------------------------------
# Fuzz test skip enforcement
# ---------------------------------------------------------------------------
def pytest_collection_modifyitems(
    config: pytest.Config,  # noqa: ARG001 - required pytest hook signature
    items: list[pytest.Item],
) -> None:
    """Skip fuzz-marked tests unless the fuzz mark is explicitly selected."""
    fuzz_skip_reason = (
        "FUZZ: run with ./scripts/fuzz_hypofuzz.sh --deep or pytest -m fuzz"
    )
    for item in items:
        if item.get_closest_marker("fuzz") is not None:
            item.add_marker(pytest.mark.skip(reason=fuzz_skip_reason))


# ---------------------------------------------------------------------------
# SKIP-BREAKDOWN reporting (consumed by scripts/test.sh)
# ---------------------------------------------------------------------------
def pytest_terminal_summary(
    terminalreporter: pytest.TerminalReporter,
    exitstatus: int,  # noqa: ARG001 - required pytest hook signature
    config: pytest.Config,  # noqa: ARG001 - required pytest hook signature
) -> None:
    """Emit structured skip breakdown for agent-native test.sh parsing."""
    skipped_fuzz = 0
    skipped_other = 0
    for report in terminalreporter.stats.get("skipped", []):
        longrepr = report.longrepr
        if isinstance(longrepr, tuple) and len(longrepr) == 3:
            skip_reason = str(longrepr[2])
        else:
            skip_reason = str(longrepr)
        if "FUZZ:" in skip_reason:
            skipped_fuzz += 1
        else:
            skipped_other += 1
    terminalreporter.write_line(
        f"[SKIP-BREAKDOWN] fuzz={skipped_fuzz} other={skipped_other}"
    )


# ---------------------------------------------------------------------------
# Crash recording infrastructure
# ---------------------------------------------------------------------------
def pytest_runtest_makereport(
    item: pytest.Item,
    call: pytest.CallInfo[None],
) -> None:
    """Record portable crash artefacts when a Hypothesis test fails.

    On each ``call`` phase failure, writes two files into
    ``.hypothesis/crashes/``:

    1. ``repro_crash_<hash>.py`` — a standalone reproduction script.
    2. ``repro_crash_<hash>.json`` — structured metadata (test ID, error type,
       timestamp) for audit trails and automated triage.

    The hash is derived from the test node ID so repeated failures for the
    same test overwrite rather than accumulate.
    """
    if call.when != "call" or call.excinfo is None:
        return

    crash_dir = Path(".hypothesis") / "crashes"
    crash_dir.mkdir(parents=True, exist_ok=True)

    node_id: str = item.nodeid
    crash_hash = hashlib.sha1(node_id.encode(), usedforsecurity=False).hexdigest()[:12]
    error_type = type(call.excinfo.value).__name__
    error_msg = str(call.excinfo.value)[:500]
    timestamp = time.time()

    # Reproduction script
    repro_path = crash_dir / f"repro_crash_{crash_hash}.py"
    repro_path.write_text(
        textwrap.dedent(f"""\
            # Reproduction script generated by conftest.py crash recorder.
            # Run directly: python {repro_path.name}
            # Test: {node_id}
            import pytest

            pytest.main(["-x", "--no-header", {node_id!r}])
        """),
        encoding="utf-8",
    )

    # JSON metadata
    meta_path = crash_dir / f"repro_crash_{crash_hash}.json"
    meta_path.write_text(
        json.dumps(
            {
                "test_id": node_id,
                "error_type": error_type,
                "error_message": error_msg,
                "timestamp": timestamp,
                "crash_hash": crash_hash,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
